services:
  api-service:
    container_name: api-service
    build: ./api_service
    environment:
      - PYTHONUNBUFFERED=1 # Prevent buffering of stdout and get logs immediately
    ports:
      - 8000:8000
    networks:
      - local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api_service:8000/readiness"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    
  green-agent:
    container_name: green-agent
    build: ./agents/green
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      api-service:
        condition: service_healthy       
    networks:
      - local

  red-agent:
    container_name: red-agent
    build: ./agents/red
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      api-service:
        condition: service_healthy
    networks:
      - local

networks:
  local:
    driver: bridge


